### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by IAmUnStTV**
Removed Underscore from links.
Edit: added discords heading as well

### CODE REVIEW

**Comment by IAmUnStTV** [comment]
I mean, more people might join if you _don't_ have underscores...

**Comment by jkmartindale** [comment]
> I mean, more people might join if you don't have underscores...

that's a massive stretch lol

**Comment by IAmUnStTV** [comment]
> > I mean, more people might join if you don't have underscores...
> 
> 
> 
> that's a massive stretch lol

Yeah, but why would they leave something that would annoy everyone in the back of your heads? This will fix it! _streeeeeeetttttccccchhhhhhh_

**Comment by jkmartindale** [comment]
tbh I didn't even notice the underscores until this PR arrived

**Review by KarlOfDuty — APPROVED** [review]

**Pull request merged**
